#!/bin/bash

doProtonate=0
cutRadius=5

if [ ! "$QBHOME" ]; then
    PRG=$0
    
    progdir=`dirname "$PRG"`
    if [ "$progdir" = "." ]; then
	    progdir=`pwd`
    fi
    
    if [ "`echo "$progdir" | grep -s '^/'`" ]; then
        progdir=$progdir
    else
        progdir=`pwd`/"$progdir"
    fi
    
    QBHOME=`echo "$progdir" | sed 's:/scripts$::'`
    export QBHOME
fi

errorOut()
{
    test $doProtonate -eq 1 && prProt="enabled" || prProt="disabled"

    echo
    echo "Usage: runNMRcomplex.sh --complex=FILENAME"
#   echo "12345678901234567890123456789012345678901234567890123456789012345678901234567890"
    echo
    echo "REQUIRED Command line arguments:"
    echo "  --target=FILENAME   * File corresponding to protein structure"
    echo "  --ligand=FILENAME   * File corresponding to ligand structure"
    echo
    echo "Optional Command line arguments:"
    echo "  --radius=#          * Radius around ligand to include.  Default=${cutRadius}"
    echo "  --enableProtonate   * enable protonation                Default=${prProt}"
    echo
    echo "For help, email support@quantumbioinc.com"
    echo 
    exit 1
}

while test $# -gt 0 ; do
    case "$1" in
        -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
        *) optarg= ;;
    esac
    case $1 in
        --help)
            errorOut
            ;;
        --radius=*)
            cutRadius=$optarg
            ;;
        --enableProtonate)
            doProtonate=1
            ;;
        --disableProtonate)
            doProtonate=0
            ;;
        --target=*)
            inTargetFile=$optarg
            ;;
        --ligand=*)
            inLigandFile=$optarg
            ;;
        *)
            echo "ERROR: $optarg option not available for --build..."
            errorOut
        esac
    shift
done

filename=$(basename "$inFile")
extension="${filename##*.}"
filename="${filename%.*}"

if [ -z "$inTargetFile" ] ; then
    echo "ERROR: Target File REQUIRED!"
    errorOut
fi

if [ -z "$inLigandFile" ] ; then
    echo "ERROR: Target File REQUIRED!"
    errorOut
fi

MOEARGS="['$inTargetFile','$inLigandFile',[enableOpt:0,enableProtonate:$doProtonate,enableLigFix:1,enableCropOnLig:1,qmcrop_radius:$cutRadius]]"
echo $MOEARGS

${QBHOME}/bin/qbmoebatch moebatch -exec "run ['$QBHOME/svl/qbPrep2Files.svl',$MOEARGS,'qbPrep2Files']" -exit

if [ -e lig_${filename}.atms ] ; then
    echo "ERROR: lig_${filename}.atms NOT FOUND!"
    errorOut
fi

if [ -e lig_${filename}.mol2 ] ; then
    echo "ERROR: lig_${filename}.mol2 NOT FOUND!"
    errorOut
fi

if [ -e mp_${filename}.atms ] ; then
    echo "ERROR: mp_${filename}.atms NOT FOUND!"
    errorOut
fi

if [ -e mp_${filename}.mol2 ] ; then
    echo "ERROR: mp_${filename}.mol2 NOT FOUND!"
    errorOut
fi

echo "Running DivCon"

atmlist=`cat lig_${filename}.atms  | tr '\n' ' ' | sed 's/    ATOM //g'`
echo "[nmr]" > lig_${filename}.ini
echo "atom=${atmlist%?}" >> lig_${filename}.ini

atmlist=`cat mp_${filename}.atms  | tr '\n' ' ' | sed 's/    ATOM //g'`
echo "[nmr]" > mp_${filename}.ini
echo "atom=${atmlist%?}" mp_${filename}.ini

divcon --nmr -i lig_${filename}.mol2 --hamiltonian=mndo_nmr -I lig_${filename}.ini  -O --standard
divcon --nmr -i mp_${filename}.mol2  --hamiltonian=mndo_nmr -I mp_${filename}.ini   -O --standard

